filter:
    excluded_paths: [__test__/*, coverage/*]
build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
